version: "3.7"

services:
  redis_dev:
    container_name: "redis-dev"
    image: redis:alpine
    ports:
      - 6380:6380
  mongodb_dev:
    container_name: "mongodb-dev"
    image: mongo:4.0.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27027-27029:27017-27019
  api_dev:
    container_name: "webapp_api-dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      LOG_LEVEL: INFO
      STAGE: dev
      MONGODB_HOST: mongodb_dev
      MONGODB_PORT: 27017
      REDIS_HOST: redis_dev
      REDIS_PORT: 6380
    restart: on-failure
    depends_on:
      - mongodb_dev

volumes:
  mongodb_data:
